# Generated by Django 4.2.17 on 2024-12-31 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bingo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingo',
            name='completed',
        ),
        migrations.AddField(
            model_name='bingo',
            name='card',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('bingo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingo')),
            ],
        ),
    ]
